INSERT INTO `brothers`(`name`, `pledge_name`, `pledge_class`, `crossing`, `alumnus`, `ethnicity`, `hometown`) VALUES   
('Tuong Phan', 'Mongo', 'Alpha', 'Spring 1997', true, 'Vietnamese', 'Queens, NY'),
('Christopher Wong', 'Crack', 'Beta', 'Fall 2001', true, 'Chinese', 'Queens, NY'),
('Kenji Yanagisawa', 'P\'zone', 'Gamma', 'Spring 2002', true, 'Japanese/Russian', 'Stormville, NY'),
('Jiang Quan Chen', 'JBL', 'Gamma', 'Spring 2002', true, 'Chinese', 'New York City'),
('Viet Nguyen', 'Quartz', 'Delta', 'Fall 2002', true, 'Vietnamese', 'Chelmsford, MA'),
('Jackson Lin', 'Burnz', 'Delta', 'Fall 2002', true, 'Chinese', 'Brooklyn, NY'),  
('Peter Tu', 'el\'Duke', 'Delta', 'Fall 2002', true, 'Chinese', 'Braintree, MA'),
('Kuang Zhu Yang', 'Desperado', 'Delta', 'Fall 2002', true, 'Chinese', 'Brooklyn, NY'),
('Daniel Ling', 'Otter', 'Delta', 'Fall 2002', true, 'Chinese', 'Holtsville, NY'),
('David Cheung', 'A.I.', 'Delta ', 'Fall 2002', true, 'Chinese', 'Lexington, MA'),
('Bao-An Nguyen', 'Ghost', 'Zeta', 'Fall 2003', true, 'Vietnamese', 'Dover, NJ'),
('James Ku', 'HOVA', 'Zeta', 'Fall 2003', true, 'Chinese', 'Queens, NY'),
('Brady Chan', 'Gadget', 'Zeta', 'Fall 2003', true, 'Chinese', 'Poughkeepsie, NY'),
('Ronald Yoon', 'Gridlock', 'Zeta', 'Fall 2003', true, 'Korean', 'Great Neck, NY'),
('Daniel Wong', 'Project', 'Zeta', 'Fall 2003', true, 'Chinese', 'Bayside, NY'),
('Henry Kwan', 'Diablo', 'Zeta', 'Fall 2003', true, 'Chinese', 'Brooklyn, NY'),
('Clifton Dong', 'Tigger', 'Zeta', 'Fall 2003', true, 'Chinese', 'Fresh Meadows, NY'),
('Andrew Ku', 'Virus', 'Eta', 'Fall 2004', true, 'Chinese', 'Queens, NY'),
('Victor Kong', 'Plaque', 'Eta', 'Fall 2004', true, 'Chinese', 'New York, NY'),
('Nathan Tam', 'Magnus', 'Eta', 'Fall 2004', true, 'Chinese', 'Staten Island, NY'),
('Jee Ho Kim', 'Sad Panda', 'Eta', 'Fall 2004', true, 'Korean', 'Holden, NY'),
('Geoffrey Abella', 'Diglett', 'Eta', 'Fall 2004', true, 'Filipino', 'New Hyde Park, NY'),
('Jonathon Wu', 'Roxbury', 'Theta', 'Fall 2005', true, 'Chinese', 'Chershire, CT'),
('Jason Ching', 'DUBZ', 'Theta', 'Fall 2005', true, 'Chinese', 'Fresh Meadows, NY'),
('Kevin Eng', 'Xzibit', 'Iota', 'Fall 2006', true, 'Chinese', 'Brooklyn, NY'),
('Sze Yin Tam', 'Half-Life', 'Iota', 'Fall 2006', true, 'Chinese', 'Brooklyn, NY'),
('Andrew Kayserian', 'Gateway', 'Iota', 'Fall 2006', true, 'Armenian', 'Queens, NY'),
('Keve G. Zoltani', 'Syndrome', 'Iota', 'Fall 2006', true, 'Hungarian', 'Luterville, MD'),
('Saadat Kalam', 'Ali-Q', 'Kappa', 'Fall 2007', true, 'Bengali', 'Queens, NY'),
('Justin Chung', 'LAPSE', 'Kappa', 'Fall 2007', true, 'Korean', 'Loudonville, NY'),
('Stephen Chiang', 'T-Mobile', 'Lambda', 'Fall 2008', true, 'Taiwanese', 'Lexington, MA'),
('Gavin Templer', 'Mad Hatter', 'Mu', 'Spring 2009', true, 'Jamaican', 'Kingston, Jamaica'),
('Clifford Chen', 'Honos', 'Nu', 'Fall 2009', true, 'Taiwanese', 'Palo Alto, CA'),
('Marcus Wong', 'Reverb', 'Nu', 'Fall 2009', true, 'Cantonese', 'San Jose, CA'),
('Brian Yu', 'Bumblebee', 'Omicron', 'Fall 2010', true, 'Chinese', 'Nashua, NH'),
('Timothy Lim', 'Fury', 'Omicron', 'Fall 2010', true, 'Chinese', 'West Orange, NJ'),
('Phillip Kuang', 'Immortal', 'Omicron', 'Fall 2010', true, 'Chinese/Cambodian', 'Flushing, NY'),
('Magesh Alagiriraj', 'Trident', 'Omicron', 'Fall 2010', true, 'Indian', 'Queens, NY'),
('Jonathan Browning', 'G-Money', 'Omicron', 'Fall 2010', true, 'Korean/American', 'Busan, South Korea'),
('Michael Wang', 'BRAWL', 'Rho', 'Fall 2011', true, 'Chinese', 'Durham, NC'),
('Justin Stein', 'Inifiniti', 'Rho', 'Fall 2011', true, 'German/Austrian', 'Ann Arbor, MI'),
('Paul Ignatenko', 'DuPont', 'Rho', 'Fall 2011', true, 'Ukranian', 'Redding CT'),
('Jonathan Chu', 'Headshot', 'Sigma', 'Fall 2012', true, 'Cantonese', 'Los Angeles, CA'),
('Brandon Sung', 'Crossfire', 'Sigma', 'Fall 2012', true, 'Korean', 'Old Tappan, NJ')
