INSERT INTO `brothers`(`name`, `pledge_name`, `pledge_class`, `crossing`, `alumnus`, `ethnicity`, `hometown`, `major`) VALUES   
('Tuong Phan', 'Mongo', 'Alpha', 'Spring 1997', true, 'Vietnamese', 'Queens, NY', ''),
('Christopher Wong', 'Crack', 'Beta', 'Fall 2001', true, 'Chinese', 'Queens, NY', 'Computer & Systems Engineering'),
('Kenji Yanagisawa', 'P\'zone', 'Gamma', 'Spring 2002', true, 'Japanese/Russian', 'Stormville, NY', 'Electrical Engineering'),
('Jiang Quan Chen', 'JBL', 'Gamma', 'Spring 2002', true, 'Chinese', 'New York City', 'Electrical Engineering'),
('Viet Nguyen', 'Quartz', 'Delta', 'Fall 2002', true, 'Vietnamese', 'Chelmsford, MA', 'Computer Science/Computer & Systems Engineering'),
('Jackson Lin', 'Burnz', 'Delta', 'Fall 2002', true, 'Chinese', 'Brooklyn, NY', 'Mechanical Engineering/Science, Technology & Society'),  
('Peter Tu', 'el\'Duke', 'Delta', 'Fall 2002', true, 'Chinese', 'Braintree, MA', 'Aeronautical Engineering/Mechanical Engineering'),
('Kuang Zhu Yang', 'Desperado', 'Delta', 'Fall 2002', true, 'Chinese', 'Brooklyn, NY', 'Business Management & Marketing'),
('Daniel Ling', 'Otter', 'Delta', 'Fall 2002', true, 'Chinese', 'Holtsville, NY', 'Computer Science'),
('David Cheung', 'A.I.', 'Delta ', 'Fall 2002', true, 'Chinese', 'Lexington, MA', 'Computer & Systems Engineering/Electrical Engineering'),
('Bao-An Nguyen', 'Ghost', 'Zeta', 'Fall 2003', true, 'Vietnamese', 'Dover, NJ', 'Computer Science/Computer & Systems Engineering'),
('James Ku', 'HOVA', 'Zeta', 'Fall 2003', true, 'Chinese', 'Queens, NY', 'Civil Engineering'),
('Brady Chan', 'Gadget', 'Zeta', 'Fall 2003', true, 'Chinese', 'Poughkeepsie, NY', 'Computer Science'),
('Ronald Yoon', 'Gridlock', 'Zeta', 'Fall 2003', true, 'Korean', 'Great Neck, NY', 'Economics'),
('Daniel Wong', 'Project', 'Zeta', 'Fall 2003', true, 'Chinese', 'Bayside, NY', 'Electrical Engineering'),
('Henry Kwan', 'Diablo', 'Zeta', 'Fall 2003', true, 'Chinese', 'Brooklyn, NY', 'Electrical Engineering'),
('Clifton Dong', 'Tigger', 'Zeta', 'Fall 2003', true, 'Chinese', 'Fresh Meadows, NY', 'Computer Science'),
('Andrew Ku', 'Virus', 'Eta', 'Fall 2004', true, 'Chinese', 'Queens, NY', 'Mechanical Engineering'),
('Victor Kong', 'Plaque', 'Eta', 'Fall 2004', true, 'Chinese', 'New York, NY', 'Information Technology'),
('Nathan Tam', 'Magnus', 'Eta', 'Fall 2004', true, 'Chinese', 'Staten Island, NY', 'Management Information Systems'),
('Jee Ho Kim', 'Sad Panda', 'Eta', 'Fall 2004', true, 'Korean', 'Holden, NY', 'Mechanical Engineering'),
('Geoffrey Abella', 'Diglett', 'Eta', 'Fall 2004', true, 'Filipino', 'New Hyde Park, NY', 'Physics'),
('Jonathon Wu', 'Roxbury', 'Theta', 'Fall 2005', true, 'Chinese', 'Chershire, CT', 'Computer & Systems Engineering/Electrical Engineering'),
('Jason Ching', 'DUBZ', 'Theta', 'Fall 2005', true, 'Chinese', 'Fresh Meadows, NY', 'Computer Science/Computer & Systems Engineering'),
('Kevin Eng', 'Xzibit', 'Iota', 'Fall 2006', true, 'Chinese', 'Brooklyn, NY', 'Mechanical Engineering'),
('Sze Yin Tam', 'Half-Life', 'Iota', 'Fall 2006', true, 'Chinese', 'Brooklyn, NY', 'Computer & Systems Engineering/Electrical Engineering'),
('Andrew Kayserian', 'Gateway', 'Iota', 'Fall 2006', true, 'Armenian', 'Queens, NY', 'Biomedical Engineering'),
('Keve G. Zoltani', 'Syndrome', 'Iota', 'Fall 2006', true, 'Hungarian', 'Luterville, MD', 'Bioinformatics'),
('Saadat Kalam', 'Ali-Q', 'Kappa', 'Fall 2007', true, 'Bengali', 'Queens, NY', 'Biomedical Engineering'),
('Justin Chung', 'LAPSE', 'Kappa', 'Fall 2007', true, 'Korean', 'Loudonville, NY', 'Biology/Pre-Med'),
('Stephen Chiang', 'T-Mobile', 'Lambda', 'Fall 2008', true, 'Taiwanese', 'Lexington, MA', 'Computer & Systems Engineering'),
('Gavin Templer', 'Mad Hatter', 'Mu', 'Spring 2009', true, 'Jamaican', 'Kingston, Jamaica', 'Computer Science/EMAC'),
('Clifford Chen', 'Honos', 'Nu', 'Fall 2009', true, 'Taiwanese', 'Palo Alto, CA', 'Management'),
('Marcus Wong', 'Reverb', 'Nu', 'Fall 2009', true, 'Cantonese', 'San Jose, CA', 'Computer Science'),
('Brian Yu', 'Bumblebee', 'Omicron', 'Fall 2010', true, 'Chinese', 'Nashua, NH', 'Computer & Systems Engineering/Electrical Engineering'),
('Timothy Lim', 'Fury', 'Omicron', 'Fall 2010', true, 'Chinese', 'West Orange, NJ', 'Physics'),
('Phillip Kuang', 'Immortal', 'Omicron', 'Fall 2010', true, 'Chinese/Cambodian', 'Flushing, NY', 'Computer & Systems Engineering'),
('Magesh Alagiriraj', 'Trident', 'Omicron', 'Fall 2010', true, 'Indian', 'Queens, NY', 'Mechanical Engineering'),
('Jonathan Browning', 'G-Money', 'Omicron', 'Fall 2010', true, 'Korean/American', 'Busan, South Korea', 'Biomedical Engineering'),
('Michael Wang', 'BRAWL', 'Rho', 'Fall 2011', false, 'Chinese', 'Durham, NC' , 'Mechanical Engineering'),
('Justin Stein', 'Inifiniti', 'Rho', 'Fall 2011', true, 'German/Austrian', 'Ann Arbor, MI', 'Mechanical Engineering'),
('Paul Ignatenko', 'DuPont', 'Rho', 'Fall 2011', true, 'Ukranian', 'Redding CT', 'Computer Science'),
('Jonathan Chu', 'Headshot', 'Sigma', 'Fall 2012', true, 'Cantonese', 'Los Angeles, CA', 'Business'),
('Brandon Sung', 'Crossfire', 'Sigma', 'Fall 2012', true, 'Korean', 'Old Tappan, NJ', 'Undeclared'),
('Edwin Chen', 'Mr. Mime', 'Phi', 'Fall 2014', false, 'Chinese', 'Brooklyn, NY', 'Computer & Systems Engineering/Electrical Engineering'),
('George Qu', 'Tortuga', 'Phi', 'Fall 2014', true, 'Chinese', 'Stamford, CT', 'Biomedical Engineering'),
('William Chang', 'Metapod', 'Phi', 'Fall 2014', false, 'Taiwanese', 'Poughkeepsie, NY', 'Mechanical Engineering'),
('Brian Shiao', 'Lucian', 'Phi', 'Fall 2014', false, 'Chinese', 'Lexington, MA', 'Biomedical Engineering'),
('Nicholas Choi', 'BAMBOO', 'Phi', 'Fall 2014', false, 'Chinese/French Canadian', 'Boston, MA', 'Electrical Engineering'),
('Danny Li', 'Mizu', 'Psi', 'Spring 2016', false, 'Chinese', 'Fort Lee, NJ', 'Computer Science'),
('Johnson Liu', 'Yeti', 'Psi', 'Spring 2016', false, 'Chinese', 'Brooklyn, NY', 'Mechanical Engineering')
